In [ ]:

# import numpy as np
# temps = np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])
# print(temps) 
# print("平均气温为：",np.mean(temps))
# print("最大气温为：",np.max(temps))
# print("最小气温为：",np.min(temps))
# print("气温超过30℃的次数为：",np.sum(temps>30))
# print("气温超过30℃的次数为：",np.count_nonzero(temps>30))
# print(sum(np.where(temps > 30,True,False)))


[10 12 14 16 18 20 22 24 26 28 30 32]
平均气温为： 21.0
最大气温为： 32
最小气温为： 10
气温超过30℃的次数为： 1
气温超过30℃的次数为： 1
1


In [ ]:

'''
生成一个(5,5)的随机数组,范围[0,20)。
- 找出数组中大于 10 的元素。
- 将所有大于 10 的元素替换为 0。
'''
import numpy as np
arr = np.random.randint(0,20,(5,5))
print(arr)
print("大于10的元素为：",arr[arr>10])
arr = np.where(arr > 10, 0, arr)
print("将所有大于10的元素替换为0后为：", arr)
print(arr)

[[15  7 16 17  1]
 [ 0 15 16  2 10]
 [17  9 13 19  3]
 [14  8 15 14 14]
 [11  1  1  8  1]]
大于10的元素为： [15 16 17 15 16 17 13 19 14 15 14 14 11]
将所有大于10的元素替换为0后为： [[ 0  7  0  0  1]
 [ 0  0  0  2 10]
 [ 0  9  0  0  3]
 [ 0  8  0  0  0]
 [ 0  1  1  8  1]]
[[ 0  7  0  0  1]
 [ 0  0  0  2 10]
 [ 0  9  0  0  3]
 [ 0  8  0  0  0]
 [ 0  1  1  8  1]]
